### ISSUE TITLE
Adding solution to project euler problem 2 in c++

### ISSUE THREAD

**Issue by AryanKansagara** [ankur-kayal/project-euler#2]

**Comment by AryanKansagara** [comment]
Can You assign this to me ?

**Comment by ankur-kayal** [comment]
@AryanKansagara done

please follow the contribution guidelines before contributing.

**Comment by AryanKansagara** [comment]
Thanks !!

**Comment by ankur-kayal** [comment]
Please mention the language in which you are going to contribute in

**Comment by AryanKansagara** [comment]
Done
